// ts-next-graphql/src/pages/index.tsx
import React from 'react';
import FlexContainer from '../components/flex-container';
import PaddedPaper from '../components/padded-paper';

// styles

const Landing = () => {
  return (
    <FlexContainer>
      <PaddedPaper elevation={3}>
        <p>Hello there!!</p>
      </PaddedPaper>
    </FlexContainer>
  );
};

export default Landing;

// vue-nuxt-base/pages/index.vue
<script>
// imports
import PaddedPaper from '../components/padded-paper';
import FlexContainer from '../components/flex-container';

// component
export default {
  components: { PaddedPaper, FlexContainer },
  render: function (h) {
    return (
      <FlexContainer>
        <PaddedPaper>
          <h3>Hello World</h3>
        </PaddedPaper>
      </FlexContainer>
    );
  },
};
</script>

<style>
.index-button {
  @apply inline-block m-2;
}
</style>
