// react-nextjs-express-d3/src/pages/charts/norm-stack-bar-chart.js
// package imports
import React, { useState, useEffect } from "react";
import * as d3 from "d3";
import NormStackBarChart from "../../components/charts/norm-stack-bar-chart";

// data
const csvStaticFilePath = "/data/us-population-state-age.csv";

// component
const NormStackBarChartPage = () => {
  // data
  const [data, setData] = useState([]);
  // fetch data
  useEffect(() => {
    const getData = async () => {
      const csvFile = await fetch(csvStaticFilePath); // csv with 2 columns
      const csvText = await csvFile.text(); // csv as string
      const csvData = d3.csvParse(
        csvText, // csv string to parse
        (d, i, columns) => (
          d3.autoType(d), (d.total = d3.sum(columns, (c) => d[c])), d
        )
      );
      const sortedCsvData = csvData.sort(
        (a, b) => b["<10"] / b.total - a["<10"] / a.total
      );
      setData(sortedCsvData);
    };
    getData();
  }, []);
  // jsx
  return (
    <div>
      <NormStackBarChart data={data} />
    </div>
  );
};

export default NormStackBarChartPage;

// old/ui/vue-nuxt-jsx-express-d3/pages/charts/norm-stack-bar-chart.vue
<script>
// imports
import NormStackBarChart from '../../components/charts/norm-stack-bar-chart';
import * as d3 from 'd3';

// component
export default {
  components: { NormStackBarChart },
  head() {
    return {
      title: 'D3 -- Norm Stack Bar Chart',
    };
  },
  data() {
    return {
      data: null,
    };
  },
  async mounted() {
    const csvStaticFilePath = '/data/us-population-state-age.csv';
    const csvFile = await fetch(csvStaticFilePath);
    const csvText = await csvFile.text();
    console.log('TCL: mounted -> csvText', csvText);
    const csvData = d3.csvParse(
      csvText,
      (d, i, columns) => (d3.autoType(d), (d.total = d3.sum(columns, (c) => d[c])), d),
    );
    const sortedCsvData = csvData.sort((a, b) => b['<10'] / b.total - a['<10'] / a.total);
    this.data = sortedCsvData;
  },
  render(h) {
    return (
      <div>
        <NormStackBarChart data={this.data} />
      </div>
    );
  },
};
</script>
