// vue-nuxt-express-d3/pages/charts/donut-chart.vue
<script>
// imports
import DonutChart from '../../components/charts/donut-chart';
import * as d3 from 'd3';

// component
export default {
  components: { DonutChart },
  data() {
    return {
      data: null,
    };
  },
  async mounted() {
    const csvStaticFilePath = '/data/population-by-age.csv';
    const csvFile = await fetch(csvStaticFilePath);
    const csvText = await csvFile.text();
    const csvData = d3.csvParse(csvText, d3.autoType);
    this.data = csvData;
  },
  render(h) {
    return (
      <div>
        <DonutChart data={this.data} />
      </div>
    );
  },
};
</script>

// react-nextjs-express-d3/src/pages/charts/donut-chart.js
// package imports
import React, { useState, useEffect } from "react";
import * as d3 from "d3";
import DonutChart from "../../components/charts/donut-chart";

// data fp
const csvStaticFilePath = "/data/population-by-age.csv";

// component
const DonutChartPage = () => {
  // data
  const [data, setData] = useState([]);
  // fetch data
  useEffect(() => {
    const getData = async () => {
      const csvFile = await fetch(csvStaticFilePath); // csv with 2 columns
      const csvText = await csvFile.text(); // csv as string
      const csvData = d3.csvParse(
        csvText, // csv string to parse
        d3.autoType
      );
      setData(csvData);
    };
    getData();
  }, []);
  // jsx
  return (
    <div>
      <DonutChart data={data} />
    </div>
  );
};

export default DonutChartPage;
