// vue-nuxt-express-d3/pages/charts/hist-kde-chart.vue
<script>
// imports
import HistKDEChart from '../../components/charts/hist-kde-chart';
import * as d3 from 'd3';

// component
export default {
  components: { HistKDEChart },
  data() {
    return {
      data: null,
    };
  },
  async mounted() {
    const jsonStaticFilePath = '/data/old-faithful.json';
    const jsonFile = await fetch(jsonStaticFilePath);
    const jsonData = await jsonFile.json();
    this.data = jsonData;
  },
  render(h) {
    return (
      <div>
        <HistKDEChart data={this.data} />
      </div>
    );
  },
};
</script>

// react-nextjs-express-d3/src/pages/charts/hist-kde-chart.js
// package imports
import React, { useState, useRef, useEffect } from "react";
import HistKDEChart from "../../components/charts/hist-kde-chart";

// data
const jsonStaticFilePath = "/data/old-faithful.json";

// main component
const HistKDEChartPage = () => {
  // data
  const [data, setData] = useState([]);
  // fetch data
  useEffect(() => {
    const getData = async () => {
      const jsonFile = await fetch(jsonStaticFilePath);
      const jsonData = await jsonFile.json();
      setData(jsonData);
    };
    getData();
  }, []);
  // jsx
  return (
    <div>
      <HistKDEChart data={data} />
    </div>
  );
};

export default HistKDEChartPage;
