// vue-nuxt-express-d3/pages/charts/scatter-plot.vue
<script>
// imports
import ScatterPlot from '../../components/charts/scatter-plot'
import * as d3 from 'd3'

// component
export default {
  components: { ScatterPlot },
  // state
  data() {
    return {
      data: null,
    }
  },
  // nuxt lifecycle method (for fetching)
  async mounted() {
    const csvStaticFilePath = '/data/iris.csv'
    const csvFile = await fetch(csvStaticFilePath) // csv with 2 columns
    const csvText = await csvFile.text() // csv as string
    const csvData = d3.csvParse(
      csvText, // csv string to parse
      d3.autoType // callback
    )
    this.data = csvData
  },
  render(h) {
    return (
      <div>
        <ScatterPlot data={this.data} />
      </div>
    )
  },
}
</script>

// react-nextjs-express-d3/src/pages/charts/scatter-plot.js
// package imports
import React, { useState, useEffect } from "react";
import * as d3 from "d3";
import ScatterPlot from "../../components/charts/scatter-plot";

// data fp
const csvStaticFilePath = "/data/iris.csv";

// component
const ScatterPlotPage = () => {
  // data
  const [data, setData] = useState([]);
  // fetch data
  useEffect(() => {
    const getData = async () => {
      const csvFile = await fetch(csvStaticFilePath); // csv with 2 columns
      const csvText = await csvFile.text(); // csv as string
      const csvData = d3.csvParse(
        csvText, // csv string to parse
        d3.autoType // callback
      );
      setData(csvData);
    };
    getData();
  }, []);
  // jsx
  return (
    <div>
      <ScatterPlot data={data} />
    </div>
  );
};

export default ScatterPlotPage;
