// ui/react-nextjs-express-d3/src/pages/charts/stacked-bar-chart.js
// package imports
import React, { useState, useEffect } from 'react';
import * as d3 from 'd3';
import StackedBarChart from '../../components/charts/stacked-bar-chart';

// data
const csvStaticFilePath = '/data/us-population-state-age.csv';

// main component
const StackedBarChartPage = () => {
  // data
  const [data, setData] = useState([]);
  // fetch data
  useEffect(() => {
    const getData = async () => {
      const csvFile = await fetch(csvStaticFilePath); // csv with 2 columns
      const csvText = await csvFile.text(); // csv as string
      const csvData = d3.csvParse(
        csvText, // csv string to parse
        (d, i, columns) => (d3.autoType(d), (d.total = d3.sum(columns, (c) => d[c])), d),
      );
      const sortedCsvData = csvData.sort((a, b) => b.total - a.total);
      setData(sortedCsvData);
    };
    getData();
  }, []);
  // jsx
  return (
    <div>
      <StackedBarChart data={data} />
    </div>
  );
};

export default StackedBarChartPage;

// vue-nuxt-express-d3/pages/charts/stacked-bar-chart.vue
<script>
// imports
import StackedBarChart from '../../components/charts/stacked-bar-chart';
import * as d3 from 'd3';

// component
export default {
  components: { StackedBarChart },
  data() {
    return {
      data: null,
    };
  },
  async mounted() {
    const csvStaticFilePath = '/data/us-population-state-age.csv';
    const csvFile = await fetch(csvStaticFilePath);
    const csvText = await csvFile.text();
    const csvData = d3.csvParse(
      csvText,
      (d, i, columns) => (d3.autoType(d), (d.total = d3.sum(columns, (c) => d[c])), d),
    );
    const sortedCsvData = csvData.sort((a, b) => b.total - a.total);
    this.data = sortedCsvData;
  },
  render(h) {
    return (
      <div>
        <StackedBarChart data={this.data} />
      </div>
    );
  },
};
</script>
