// react-nextjs-express-d3/src/pages/charts/violin-chart.js
// package imports
import React, { useState, useEffect } from "react";
import * as d3 from "d3";
import ViolinChart from "../../components/charts/violin-chart";

// data
const csvStaticFilePath = "/data/iris-data.csv";

// main component
const ViolinChartPage = () => {
  // data
  const [data, setData] = useState([]);
  // fetch data
  useEffect(() => {
    const getData = async () => {
      const csvFile = await fetch(csvStaticFilePath); // csv with 2 columns
      const csvText = await csvFile.text(); // csv as string
      const csvData = d3.csvParse(
        csvText, // csv string to parse
        d3.autoType
      );
      setData(csvData);
    };
    getData();
  }, []);
  // jsx
  return (
    <div>
      <ViolinChart data={data} />
    </div>
  );
};

export default ViolinChartPage;

// vue-nuxt-express-d3/pages/charts/violin-chart.vue
<script>
// imports
import ViolinChart from '../../components/charts/violin-chart';
import * as d3 from 'd3';

// component
export default {
  components: { ViolinChart },
  data() {
    return {
      data: null,
    };
  },
  async mounted() {
    const csvStaticFilePath = '/data/iris-data.csv';
    const csvFile = await fetch(csvStaticFilePath);
    const csvText = await csvFile.text();
    const csvData = d3.csvParse(csvText, d3.autoType);
    this.data = csvData;
  },
  render(h) {
    return (
      <div>
        <ViolinChart data={this.data} />
      </div>
    );
  },
};
</script>
