// ts-next-graphql/src/pages/index.tsx
import React from 'react';
import FlexContainer from '../components/flex-container';
import PaddedPaper from '../components/padded-paper';

// styles

const Landing = () => {
  return (
    <FlexContainer>
      <PaddedPaper elevation={3}>
        <p>Hello there!!</p>
      </PaddedPaper>
    </FlexContainer>
  );
};

export default Landing;

// ui/vue-ts-nuxt-express-base/pages/index.vue
<template>
  <FlexContainer>
    <PaddedPaper>
      <h3>Hello World</h3>
    </PaddedPaper>
  </FlexContainer>
</template>

<script lang="ts">
// imports
import PaddedPaper from '../components/padded-paper.vue';
import FlexContainer from '../components/flex-container.vue';

// component
export default {
  components: { PaddedPaper, FlexContainer },
};
</script>

<style>
.index-button {
  @apply inline-block m-2;
}
</style>
